name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: npm ci
    - name: Build dependencies
      run: npm run build
  