on:
  push:
    branches:
    - '**'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: npm ci
    - name: Build dependencies
      run: npm run build
  