name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Initializing test for PR
      uses: actions/checkout@main
    - name: Install dependencies
      run: npm ci
    - name: Making build
      run: npm run build
  